spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5434/user_db
    username: postgres
    password: postgres
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000

app:
  jwt:
    secret: "secretKey"
    tokenExpiration: 30m
    refreshTokenExpiration: 30m

  bank:
    balance:
      update: true

